### ISSUE TITLE
Bank function simply don't work on Teensy LC.

### ISSUE THREAD

**Issue by SwooshMihu** [tttapa/Control-Surface#216]
I have tried using every Bank example provided with the proper wiring yet none of them seem to work.
I will take the simplest example, using the Bank.io example with 2 potentiometer and the 2 buttons connected to the according A0 A1 , 2 and 3 pins and by evaluating the MIDI output using MIDI-OX monitor, the bank function does not work.

Output of MIDI-OX 
![image](https://user-images.githubusercontent.com/47503915/84531270-076c8300-aced-11ea-8b69-de603a8820cf.png)

Just to make sure that the wiring is correct, i've uploaded a program to test all of them as inputs and they work just fine.

**Comment by tttapa** [comment]
Please use the following sketch to ensure that the selector buttons are working:
```cpp
#include <Control_Surface.h> // Include the Control Surface library

template <setting_t N>
class TestSelectable : public Selectable<N> {
  void select(setting_t newsetting) override {
    Serial << "Selection " << newsetting << endl;
  }
};

TestSelectable<4> sel;

IncrementDecrementSelector<4> selector = {
    sel,
    {2, 3},     // push button pins (increment, decrement)
    Wrap::Wrap, // Wrap around
};

void setup() {
  Serial.begin(115200);
  while(!Serial);
  selector.begin();
}
 
void loop() {
  selector.update();
}
```
It should print the new selection to the serial monitor when a button is pressed.

**Comment by SwooshMihu** [comment]
Without pressing any buttons, it does this
![image](https://user-images.githubusercontent.com/47503915/84532376-d2f9c680-acee-11ea-833b-05677d1bd41f.png)
Might it be due to imperfect contacts? I have no clue at this point.
I have tested the wiring of the buttons using  this function
![image](https://user-images.githubusercontent.com/47503915/84532481-fcb2ed80-acee-11ea-8fdf-b7ba18d324a1.png)
and it worked fine.

**Comment by tttapa** [comment]
Are your buttons normally open or normally closed? If the selection changes without you pressing the buttons, this means that pin 3 is always low, any idea why that would be the case?

**Comment by SwooshMihu** [comment]
I am using a basic arduino pushbutton with this wiring
![image](https://user-images.githubusercontent.com/47503915/84533584-181ef800-acf1-11ea-9885-e2cce61ba747.png)

I have tried with and without the resistor with the same result..

**Comment by SwooshMihu** [comment]
Fixed it, it was a wiring problem, thanks for your time!
I have just removed this wire
![image](https://user-images.githubusercontent.com/47503915/84533935-be6afd80-acf1-11ea-8033-192fde603430.png)

**Comment by tttapa** [comment]
Leave out the resistor, and connect the bottom lead of the button to ground, not 5V.

**Comment by tttapa** [comment]
> I have just removed this wire

That doesn't solve the problem, it leaves your button floating halfway.

**Comment by SwooshMihu** [comment]
yep,yep, done as you say and it works. Thank you again!
